=== VladislavYuditsky/JWD-XML-Parsing/data/flowers.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.yuditsky.com/flowers"
        xmlns:tns="http://www.yuditsky.com/flowers"
        elementFormDefault="qualified">

    <element name="flower" type="tns:Flower"/>

    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:flower"
                         minOccurs="2"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Flower">
        <sequence>
            <element name="soil" type="tns:Soil" default="podzolic"/>
            <element name="origin" type="string"/>
            <element name="growing_tipc" type="tns:GrowingTipc"/>
            <element name="visual_param" type="tns:VisualParam"/>
            <element name="multiplying" type="tns:Multiplying"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="species" type="string" use="required" default="noname"/>
        <attribute name="class" type="string" use="optional"/>
        <attribute name="family" type="string" use="optional"/>
    </complexType>

    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="podzolic"/>
            <enumeration value="unpaved"/>
            <enumeration value="sod-podzolic"/>
        </restriction>
    </simpleType>

    <complexType name="GrowingTipc">
        <sequence>
            <element name="temperature" type="int"/>
            <element name="photophilous" type="boolean"/>
            <element name="watering" type="unsignedInt"/>
        </sequence>
    </complexType>

    <complexType name="VisualParam">
        <sequence>
            <element name="stem_color" type="string"/>
            <element name="leaf_color" type="string"/>
            <element name="average_size" type="unsignedInt"/>
        </sequence>
    </complexType>

    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="leaf"/>
            <enumeration value="seed"/>
            <enumeration value="cutting"/>
            <enumeration value="bulb"/>
        </restriction>
    </simpleType>
</schema>

=== VladislavYuditsky/JWD-XML-Parsing/data/flowers.xml
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.yuditsky.com/flowers"
         xsi:schemaLocation="http://www.yuditsky.com/flowers ../data/flowers.xsd">

    <flower id="ID-1" species="Currant">
        <soil>podzolic</soil>
        <origin>Eurasia</origin>
        <growing_tipc>
            <temperature>20</temperature>
            <photophilous>true</photophilous>
            <watering>500</watering>
        </growing_tipc>
        <visual_param>
            <stem_color>green</stem_color>
            <leaf_color>green</leaf_color>
            <average_size>150</average_size>
        </visual_param>
        <multiplying>cutting</multiplying>
    </flower>

    <flower id="ID-2" species="Tulip">
        <soil>unpaved</soil>
        <origin>Iran</origin>
        <growing_tipc>
            <temperature>20</temperature>
            <photophilous>true</photophilous>
            <watering>300</watering>
        </growing_tipc>
        <visual_param>
            <stem_color>green</stem_color>
            <leaf_color>green</leaf_color>
            <average_size>40</average_size>
        </visual_param>
        <multiplying>bulb</multiplying>
    </flower>

    <flower id="ID-3" species="chamomile" class="dicotyledonous" family="aster">
        <soil>sod-podzolic</soil>
        <origin>Eurasia</origin>
        <growing_tipc>
            <temperature>17</temperature>
            <photophilous>true</photophilous>
            <watering>150</watering>
        </growing_tipc>
        <visual_param>
            <stem_color>green</stem_color>
            <leaf_color>green</leaf_color>
            <average_size>10</average_size>
        </visual_param>
        <multiplying>seed</multiplying>
    </flower>

    <flower id="ID-4" species="Vasileck" class="dicotyledonous">
        <soil>podzolic</soil>
        <origin>Europe</origin>
        <growing_tipc>
            <temperature>12</temperature>
            <photophilous>true</photophilous>
            <watering>100</watering>
        </growing_tipc>
        <visual_param>
            <stem_color>green</stem_color>
            <leaf_color>green</leaf_color>
            <average_size>10</average_size>
        </visual_param>
        <multiplying>seed</multiplying>
    </flower>

    <flower id="ID-5" species="">
        <soil>podzolic</soil>
        <origin>1</origin>
        <growing_tipc>
            <temperature>1</temperature>
            <photophilous>1</photophilous>
            <watering>1</watering>
        </growing_tipc>
        <visual_param>
            <stem_color>1</stem_color>
            <leaf_color>1</leaf_color>
            <average_size>1</average_size>
        </visual_param>
        <multiplying>leaf</multiplying>
    </flower>
</flowers>
